- name: Install Warp terminal on ubuntu
  ansible.builtin.shell: sudo apt-get install wget gpg

- name: Install Warp terminal on ubuntu 2
  ansible.builtin.shell: wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor > warpdotdev.gpg

- name: Install Warp terminal on ubuntu 3
  ansible.builtin.shell: sudo install -D -o root -g root -m 644 warpdotdev.gpg /etc/apt/keyrings/warpdotdev.gpg

- name: Install Warp terminal on ubuntu 4
  ansible.builtin.shell: sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list'

- name: Install Warp terminal on ubuntu 5
  ansible.builtin.shell: sudo apt-get install wget gpg

- name: Install Warp terminal on ubuntu 6
  ansible.builtin.shell: rm warpdotdev.gpg

- name: Install Warp terminal on ubuntu 7
  ansible.builtin.shell: sudo apt update && sudo apt install warp-terminal -y






