



- name: Install NALA
  ansible.builtin.apt:
    name: nala
    state: present
    update_cache: true

- name: Install Ansible
  ansible.builtin.apt:
    name: ansible
    state: present
    update_cache: true

- name: Install Brave browser
  ansible.builtin.shell: |
    sudo apt install curl -y

    sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

    echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

    sudo apt update

    sudo apt install brave-browser -y


- name: Install Visual Studio Code
  ansible.builtin.shell: |
    sudo apt-get install wget gpg
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
    echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
    rm -f packages.microsoft.gpg
    sudo apt install apt-transport-https
    sudo apt update
    sudo apt install code -y


- name: Copy content of directory 'files'
  copy:
    src: files/desktop # note the '/' <-- !!!
    dest: /tmp/files/

# Install dependencies (curl, gnupg)
- name: Install required dependencies
  apt:
    name:
      - curl
      - gnupg
      - software-properties-common
    state: present



# Download Terraform
- name: Download Terraform
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

# Verify fingerprint
- name: Verify fingerprint
  shell: |
    gpg --no-default-keyring \
    --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    --fingerprint  

# Add HashiCorp repository
- name: Add HashiCorp repository
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    sudo tee /etc/apt/sources.list.d/hashicorp.list > /dev/null

#  Update package list
- name: Update package list
  apt:
    update_cache: yes
# Install Terraform
- name: Install Terraform
  apt:
    name: terraform
    state: present
    update_cache: yes
    


