



- name: Install NALA
  ansible.builtin.apt:
    name: nala
    state: present
    update_cache: true

- name: Install Ansible
  ansible.builtin.apt:
    name: ansible
    state: present
    update_cache: true

- name: Install Brave browser
  ansible.builtin.shell: |
    sudo apt install curl -y

    sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

    echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

    sudo apt update

    sudo apt install brave-browser -y


- name: Install Visual Studio Code
  ansible.builtin.shell: |
    sudo apt-get install wget gpg
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
    echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" |sudo tee /etc/apt/sources.list.d/vscode.list > /dev/null
    rm -f packages.microsoft.gpg
    sudo apt install apt-transport-https
    sudo apt update
    sudo apt install code -y


- name: Copy content of directory 'files'
  copy:
    src: files/ # note the '/' <-- !!!
    dest: /tmp/files/




